1) Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np
import pandas as pd

a = np.arange(12, 24)

2) Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [8]:
a1 = a.reshape(3, 4)
a2 = a.reshape(4, 3)
a3 = a.reshape(6, 2)
a4 = a.reshape(2, 6)
a5 = a.reshape(12, 1)
a1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

3) Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [7]:
a6 = a.reshape(3, -1)
a7 = a.reshape(-1, 3)
a8 = a.reshape(6, -1)
a9 = a.reshape(-1, 6)
a10 = a.reshape(12, -1)
a8

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

4) Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Нет, это будет двумерный массив с 12 строками. Пример массив a5

In [10]:
a5.ndim

2

5) Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [11]:
b = np.random.randn(3, 4)
b.flatten()

array([-0.25788418,  0.27460581,  0.39643896, -0.80332327,  0.84495474,
        1.39668449, -0.24023308,  0.14239434,  0.99135466,  0.0524036 ,
       -0.61460359,  0.0165898 ])

6) Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [10]:
a = np.arange(20, 0 , -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7) Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

Не вижу между ними разнцы

In [13]:
b = np.arange(20, 1, -2)
b.reshape(1, 10)


array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

8) Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [16]:
a = np.zeros((3, 2))
b = np.ones((2, 2))
v = np.vstack((a, b))
v.size

10

9) Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 
Какой размер имеет матрица B? 
16 (4x4)
Получится ли вычислить обратную матрицу для матрицы B и почему?
Нет, потому что матрица квадратная и ее определитель равено 0

In [12]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.T
B = np.matmul(A, At)
B.size
np.linalg.det(B)

0.0

10) Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [18]:
np.random.seed(42)
np.random.rand(10)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

11) Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [29]:
c = np.random.randint(0, 16, (1, 16))
c

array([[ 2,  6,  4,  8,  6,  1,  3,  8, 11, 13,  1,  9,  8,  9,  4,  1]])

12) Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [37]:
C = c.reshape(4, 4)
D = B + C*10
np.linalg.det(D) #определитель
np.linalg.matrix_rank(D) #ранг
D_inv = np.linalg.inv(D) #обратная матрица
D_inv

array([[-0.04476419,  0.00300755,  0.01280542,  0.00172701],
       [ 0.00654193, -0.0124515 ,  0.00479828,  0.00106867],
       [-0.01213004, -0.00071191, -0.00745759,  0.01203385],
       [ 0.02142138,  0.007956  , -0.00183375, -0.00786062]])

13) Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [46]:
for i in range(4):
  for j in range(4):
    if D_inv[i, j] > 0:
        D_inv[i, j] = 1
    else: D_inv[i, j] = 0
print(D_inv)
E = np.where(D_inv, B, C)
print(B)
print(C)
print(E)

[[0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [0. 0. 0. 1.]
 [1. 1. 0. 0.]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 2  6  4  8]
 [ 6  1  3  8]
 [11 13  1  9]
 [ 8  9  4  1]]
[[  2  14  23  32]
 [ 14   1  86 122]
 [ 11  13   1 212]
 [ 32 122   4   1]]
