1а) Создаем матрицу 

In [5]:
import numpy as np
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])

1

1b) Считаем среднее по столбцам

In [6]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

2) Вычитаем среднее значение из соответсвующих столбцов используя коцепцию broadcasting

In [7]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

3) Находим скалярное произведение столбцов и вычисляем несмещенную ковариацию

In [26]:
a_centered_sp = a_centered[:, 0] * a_centered[:, 1]
a_centered_sp
cov_1 = a_centered_sp.sum() / (a.shape[0] - 1) 
cov_1

array([ 2.4, -0. ,  2.6,  1.6,  1.4])

4) Проверяем полученное значение ковариации с помощью функции numpy np.cov

In [25]:
cov_2 = np.cov(a.T)[0, 1] 
cov_2

2.0